### ISSUE TITLE
dh: error: Compatibility levels before 5 are no longer supported (level 1 requested)

### ISSUE THREAD

**Issue by TheAquabat** [Fincer/dxvk-wine-autobuilder#2]
I can't finish compiling I get this error

> dh: error: Compatibility levels before 5 are no longer supported (level 1 requested)

Kubuntu 20.4.1

**Comment by TheAquabat** [comment]
nvm solved closing this ... I needed to create a file name "compat" on debian folder with the number 9. not a bug.

**Comment by TheAquabat** [comment]
I'm reopening this because it's defeats the purpose of this program not only in the root directory you have to create the compat file but in each source directory. It's suppose to be easy, but it is not .

**Comment by Fincer** [comment]
Thanks for making me aware of this issue. I can confirm it and have addressed it in commits:

- https://github.com/Fincer/dxvk-wine-autobuilder/commit/22551ecfa17f1d2aaf51e2980d82b4c4810fdb08

- https://github.com/Fincer/dxvk-wine-autobuilder/commit/4d3c5ee12cd2424241461e9009ebd6095645f6a6

I checked the overall build process on Xubuntu 20.04 LTS and also fixed other minor issues I noticed on the way.

Hope this helps.

**Comment by TheAquabat** [comment]
Ok now it builds but I was still missing one dependency "python3-construct"
Meson says that level 9 compat is deprecated but it still builds.

**Comment by Fincer** [comment]
> I was still missing one dependcy "python3-construct"

Hmm, that's bit weird. I couldn't reproduce this one.

On my reference system (Xubuntu 20.04 LTS), I hadn't any issues regarding to missing dependencies. I don't have `python3-construct` installed, and can't see any referral to it in [meson](https://github.com/mesonbuild/meson) & [glslang](https://github.com/KhronosGroup/glslang) GitHub repositories. Can't see any warnings or failures neither.

Just asking for out of curiosity: At which point of the installation process did you get the message (e.g. during `meson`/`glslang`/`wine`/`dxvk-git` dependency installation?) I'd like to fix the issue if there was one.

> Meson says that level 9 compat is deprecated but it's still builds.

Hmm, I didn't notice such message. However, this Debian bug tracker issue may be relevant: [#950453 - Mark debhelper compatibility level 9 as deprecated](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=950453)

I bumped `compat` level up to 12. Compiles fine at my end.

**Comment by TheAquabat** [comment]
I don't know then dependency hell gives my headaches 🤯😣 😂 My system is pretty messed up with dependencies.
 I'm not sure so I'm closing this.

**Comment by Fincer** [comment]
I don't know your system but at some point in a Debian-alike system life time, `dpkg` and `apt` _may_ easily get to non-working or broken state, depending on multiple factors (like conflicting package versions). If you have such issues, I hope you get your system to stable state again.

I tested the commits on a fresh Xubuntu 20.04 LTS, installed on a virtual machine. So yeah, we may have different starting point.

I'm aware my Wine/DXVK shell scripts are not perfect either. Therefore, considerable testing would be required. I may consider implementing a simple logging system at some point in the future to mitigate errors people may have with these scripts.
